import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Магазин одежды</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>
          Добро пожаловать, покупатель!
        </h3>
        <span>Основной контент</span>
        <Link href='products'>Все товары</Link>
      </main>

      <footer className={styles.footer}>
        Подвал
      </footer>
    </div>
  )
}
